# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 18, 11, 55, 416968, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheme',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
