from __future__ import unicode_literals
from django.conf import settings
from django.db import models

class Info(models.Model):
    category = models.CharField(max_length=3)
    aadhar = models.IntegerField()
    state = models.CharField(max_length=20)
    hof_name = models.CharField(max_length=50)
    house_number = models.CharField(max_length=5)
    relations = models.CharField(max_length=20)
    date_of_birth =  models.CharField(max_length=20)
    eco_group = models.CharField(max_length=4)
    building_number = models.IntegerField()
    bhamasha_id = models.CharField(max_length=13)
    street_name = models.CharField(max_length=20)
    ifsc_code = models.CharField(max_length=10)
    my_id = models.CharField(max_length=6)
    family_idno = models.CharField(max_length=10)
    pincode = models.IntegerField()
    landline_no = models.IntegerField()
    village_name = models.CharField(max_length=20)
    gp_ward = models.CharField(max_length=15)
    email = models.CharField(max_length=50)
    spouse_name = models.CharField(max_length=20)
    is_rural = models.CharField(max_length=4)
    district = models.CharField(max_length=10)
    edu_info = models.CharField(max_length=15)
    account_number = models.IntegerField()
    address = models.CharField(max_length=100)
    income = models.CharField(max_length=100)
    bank_name = models.CharField(max_length=40)
    landmark = models.CharField(max_length=40)
    ration_card_no = models.CharField(max_length=15)
    name_extra = models.CharField(max_length=24)
    mobile_no = models.IntegerField()
    gender = models.CharField(max_length=8)
    father_name = models.CharField(max_length=50)
    fax_no = models.IntegerField()
    block_city = models.CharField(max_length=30)
    created_date = models.DateTimeField(auto_now=False, auto_now_add=True,)
    def __unicode__(self):
        return '%s' % ( self.hof_name)

class FamilyInfo(models.Model):
    family = models.ForeignKey('Info', related_name='familyinfo', on_delete=models.CASCADE)
    category = models.CharField(max_length=3)
    aadhar = models.IntegerField()
    state = models.CharField(max_length=20)
    hof_name = models.CharField(max_length=50)
    house_number = models.CharField(max_length=5)
    relations = models.CharField(max_length=20)
    date_of_birth =  models.CharField(max_length=20)
    eco_group = models.CharField(max_length=4)
    building_number = models.IntegerField()
    bhamasha_id = models.CharField(max_length=13)
    street_name = models.CharField(max_length=20)
    ifsc_code = models.CharField(max_length=10)
    my_id = models.CharField(max_length=6)
    family_idno = models.CharField(max_length=10)
    pincode = models.IntegerField()
    landline_no = models.IntegerField()
    village_name = models.CharField(max_length=20)
    gp_ward = models.CharField(max_length=15)
    email = models.CharField(max_length=50)
    spouse_name = models.CharField(max_length=20)
    is_rural = models.CharField(max_length=4)
    district = models.CharField(max_length=10)
    edu_info = models.CharField(max_length=15)
    account_number = models.IntegerField()
    address = models.CharField(max_length=100)
    income = models.CharField(max_length=100)
    bank_name = models.CharField(max_length=40)
    landmark = models.CharField(max_length=40)
    ration_card_no = models.CharField(max_length=15)
    name_extra = models.CharField(max_length=24)
    mobile_no = models.IntegerField()
    gender = models.CharField(max_length=8)
    father_name = models.CharField(max_length=50)
    fax_no = models.IntegerField()
    block_city = models.CharField(max_length=30)
    created_date = models.DateTimeField('profile creation date')


    def __unicode__(self):
        return '%s' % ( self.hof_name)
